import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | NepaCal',
  description: 'NepaCal terms of service — conditions for using Nepal\\'s free calculator platform.',
  alternates: {
    canonical: 'https://NepaCalc.com/terms/',
  },
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-16 min-h-screen">
      <h1 className="text-3xl font-black text-gray-900 mb-2">Terms of Service</h1>
      <p className="text-sm text-gray-500 font-medium mb-8">
        <strong>Last updated:</strong> May 1, 2026
      </p>

      <div className="prose prose-blue max-w-none text-gray-700 space-y-6">
        <p>By using NepaCal (nepacalc.com), you agree to the following terms. Please read them before using the site.</p>

        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4 border-b pb-2">Use of Calculators</h2>
        <p>NepaCal&apos;s calculators are provided for <strong>informational and educational purposes only</strong>. While we make every effort to ensure accuracy, the results generated by our tools should not be treated as professional financial, tax, legal, or medical advice.</p>
        <p><strong>For important decisions involving:</strong></p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Tax filing — consult a registered tax practitioner or the Inland Revenue Department (ird.gov.np)</li>
          <li>Loans and investments — consult a SEBON-registered financial advisor or your bank directly</li>
          <li>Medical or health decisions — consult a qualified healthcare professional</li>
          <li>Legal or property matters — consult a licensed lawyer or relevant government authority</li>
        </ul>

        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4 border-b pb-2">Accuracy and Liability</h2>
        <p>We update our Nepal-specific calculators with each fiscal year&apos;s government announcements. However:</p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Tax rates, government fees, and financial regulations in Nepal change periodically</li>
          <li>We cannot guarantee that all information on NepaCal is current at any given moment</li>
          <li>NepaCal and its operators are not liable for any financial loss, tax penalty, or other consequence arising from use of information on this site</li>
        </ul>
        <p>Always verify critical figures against the relevant official source before making any financial or legal decision.</p>

        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4 border-b pb-2">Intellectual Property</h2>
        <p>All content on NepaCal — including calculator logic, written explanations, blog posts, and design — is the intellectual property of NepaCal and Avash Chaudhary. You may:</p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Use the calculators freely for personal or professional purposes</li>
          <li>Share links to NepaCal pages</li>
          <li>Quote brief passages with proper attribution and a link to the source page</li>
        </ul>
        <p>You may not:</p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Copy or reproduce NepaCal&apos;s content (text, calculators, or code) on another website without permission</li>
          <li>Scrape, automate, or extract data from NepaCal in bulk</li>
          <li>Represent NepaCal&apos;s tools as your own work</li>
        </ul>

        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4 border-b pb-2">Third-Party Advertising</h2>
        <p>NepaCal displays advertisements served by Google AdSense and potentially other advertising partners. We are not responsible for the content, accuracy, or practices of advertisers. Clicking on advertisements takes you away from NepaCal — we recommend reviewing the privacy policies of any advertiser&apos;s website.</p>

        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4 border-b pb-2">External Links</h2>
        <p>NepaCal links to official government websites (IRD, NRB, DoTM) and other resources. We are not responsible for the content, availability, or accuracy of external websites.</p>

        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4 border-b pb-2">Changes to These Terms</h2>
        <p>We may update these terms periodically. Continued use of NepaCal after any update constitutes acceptance of the revised terms.</p>

        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4 border-b pb-2">Contact</h2>
        <p>For questions about these terms: <a href="mailto:admin@nepacalc.com" className="text-blue-600 hover:underline">admin@nepacalc.com</a></p>
      </div>
    </div>
  );
}
