name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Set this to your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-code: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Static Site
        run: npm run build

      - name: FTP Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: /public_html/  # Adjust this to your specific cPanel folder
          dangerous-clean-slate: false # Set to true ONLY if you want to delete existing files in public_html that are not in the repo
