name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Set this to your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Static Site
        run: npm run build
        env:
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: "calcpro-e1dd9"
          NEXT_PUBLIC_FIREBASE_DATABASE_ID: "ai-studio-d5cad48c-3132-4615-96f7-ef198596220d"
          NEXT_PUBLIC_SITE_URL: "https://nepacalc.com"
          NEXT_PUBLIC_FIREBASE_API_KEY: "AIzaSyAUAbGWU1eMw7eePLTG0D1gbQRssGqw6V8"
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "calcpro-e1dd9.firebaseapp.com"
          NEXT_PUBLIC_FIREBASE_APP_ID: "1:369907965034:web:71504a7c24a9b3690dfe13"
          NEXT_PUBLIC_GA_ID: "G-G78ED8CZ3D"

      - name: FTP Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 51.79.228.153
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: public_html/
          state-name: .ftp-deploy-sync-state-v3.json
          dangerous-clean-slate: false
          timeout: 30000
          exclude: |
            **/.htaccess
            **/cgi-bin/**
            **/.well-known/**
            **/*.log
